java jstyle.JSFormatter -ll78 *.java
del *.java
move First.java.js First.java
move BotDatabaseSecurityManager.java.js BotDatabaseSecurityManager.java
move BotSecurityException.java.js BotSecurityException.java
move BotSecurityManager.java.js BotSecurityManager.java
move BQLException.java.js BQLException.java
move Channel.java.js Channel.java
move CommandConnection.java.js CommandConnection.java
move DefaultIRCListener.java.js DefaultIRCListener.java
move DirectConnection.java.js DirectConnection.java
move DirectConnectionHandler.java.js DirectConnectionHandler.java
move EightBall.java.js EightBall.java
move IdentdThread.java.js IdentdThread.java
move IRCConnection.java.js IRCConnection.java
move IRCLine.java.js IRCLine.java
move IRCMessage.java.js IRCMessage.java
move Oak.java.js Oak.java
move OakChannelPlugin.java.js OakCommand.java
move OakCommand.java.js OakCommand.java
move OakPlugin.java.js OakPlugin.java
move OakPluginManager.java.js OakPluginManager.java
move OakUser.java.js OakUser.java
move PluginWrapper.java.js PluginWrapper.java
move PropertiesSecurityManager.java.js PropertiesSecurityManager.java
move TelnetConnection.java.js TelnetConnection.java
move TelnetListener.java.js TelnetListener.java
move DefaultOakPlugin.java.js DefaultOakPlugin.java
move IRCListener.java.js IRCListener.java
