JAVAC=javac

FRAMEWORK_SOURCES = \
org/moxy/irc/Channel.java \
org/moxy/irc/ChannelListener.java \
org/moxy/irc/ConsoleListener.java \
org/moxy/irc/DefaultIRCListener.java \
org/moxy/irc/IRCConnection.java \
org/moxy/irc/IRCLine.java \
org/moxy/irc/IRCListener.java \
org/moxy/irc/IRCMessage.java \
org/moxy/irc/IdentdThread.java \
org/moxy/irc/ListNick.java \
org/moxy/irc/OutgoingListener.java \

FRAMEWORK_CLASSES = \
org/moxy/irc/Channel.class \
org/moxy/irc/ChannelListener.class \
org/moxy/irc/ConsoleListener.class \
org/moxy/irc/DefaultIRCListener.class \
org/moxy/irc/IRCConnection.class \
org/moxy/irc/IRCLine.class \
org/moxy/irc/IRCListener.class \
org/moxy/irc/IRCMessage.class \
org/moxy/irc/IdentdThread.class \
org/moxy/irc/ListNick.class \
org/moxy/irc/OutgoingListener.class

OAKCORE_SOURCES = \
org/moxy/oak/Preferences.java \
org/moxy/oak/Oak.java \
org/moxy/oak/OakCommand.java \
org/moxy/oak/OakConfigurator.java \
org/moxy/oak/irc/IRCCommandConnection.java \
org/moxy/oak/irc/CommandConnection.java 

OAKCORE_CLASSES = \
org/moxy/oak/Preferences.class \
org/moxy/oak/Oak.class \
org/moxy/oak/OakCommand.class \
org/moxy/oak/OakConfigurator.class \
org/moxy/oak/irc/IRCCommandConnection.class \
org/moxy/oak/irc/CommandConnection.class

UTILS_SOURCES = \
org/moxy/util/Ping.java \
org/moxy/util/Pingable.java \
org/moxy/util/ThreadInteruptingVector.java \
org/moxy/util/TimeWrapper.java \
org/moxy/util/ListableProperties.java

UTILS_CLASSES = \
org/moxy/util/Ping.class \
org/moxy/util/Pingable.class \
org/moxy/util/ThreadInteruptingVector.class \
org/moxy/util/TimeWrapper.class \
org/moxy/util/ListableProperties.class

OAKPLUGINS_SOURCES = \
org/moxy/oak/plugin/ChannelPlugin.java \
org/moxy/oak/plugin/DCCChatConfigurator.java \
org/moxy/oak/plugin/DCCChatManager.java \
org/moxy/oak/plugin/DCCChatPlugin.java \
org/moxy/oak/plugin/DefaultOakPlugin.java \
org/moxy/oak/plugin/EightBall.java \
org/moxy/oak/plugin/First.java \
org/moxy/oak/plugin/OakPlugin.java \
org/moxy/oak/plugin/PartyLine2.java \
org/moxy/oak/plugin/PartyLine2Channel.java \
org/moxy/oak/plugin/PartyLine2Client.java \
org/moxy/oak/plugin/PartyLine2Server.java \
org/moxy/oak/plugin/PartyLine2User.java \
org/moxy/oak/plugin/PluginWrapper.java \
org/moxy/oak/plugin/DefaultChannelPlugin.java \
org/moxy/oak/plugin/FirstChannelPlugin.java

OAKPLUGINS_CLASSES = \
org/moxy/oak/plugin/ChannelPlugin.class \
org/moxy/oak/plugin/DCCChatConfigurator.class \
org/moxy/oak/plugin/DCCChatManager.class \
org/moxy/oak/plugin/DCCChatPlugin.class \
org/moxy/oak/plugin/DefaultOakPlugin.class \
org/moxy/oak/plugin/EightBall.class \
org/moxy/oak/plugin/First.class \
org/moxy/oak/plugin/OakPlugin.class \
org/moxy/oak/plugin/PartyLine2.class \
org/moxy/oak/plugin/PartyLine2Channel.class \
org/moxy/oak/plugin/PartyLine2Client.class \
org/moxy/oak/plugin/PartyLine2Server.class \
org/moxy/oak/plugin/PartyLine2User.class \
org/moxy/oak/plugin/PluginWrapper.class \
org/moxy/oak/plugin/DefaultChannelPlugin.class \
org/moxy/oak/plugin/FirstChannelPlugin.class

OAKSECURITY_SOURCES = \
org/moxy/oak/security/BQLException.java \
org/moxy/oak/security/BotDatabaseSecurityManager.java \
org/moxy/oak/security/BotSecurityException.java \
org/moxy/oak/security/BotSecurityManager.java \
org/moxy/oak/security/OakUser.java \
org/moxy/oak/security/PropertiesSecurityManager.java

OAKSECURITY_CLASSES = \
org/moxy/oak/security/BQLException.class \
org/moxy/oak/security/BotDatabaseSecurityManager.class \
org/moxy/oak/security/BotSecurityException.class \
org/moxy/oak/security/BotSecurityManager.class \
org/moxy/oak/security/OakUser.class \
org/moxy/oak/security/PropertiesSecurityManager.class

OAKCOMMANDPLUGS_SOURCES = \
org/moxy/oak/commandplug/CommandPlug.java \
org/moxy/oak/commandplug/ConnectionPlug.java \
org/moxy/oak/commandplug/DBCommandPlug.java \
org/moxy/oak/commandplug/DoSayCommandPlug.java \
org/moxy/oak/commandplug/ExitCommandPlug.java \
org/moxy/oak/commandplug/JoinPartCommandPlug.java \
org/moxy/oak/commandplug/KickCommandPlug.java \
org/moxy/oak/commandplug/ModerCommandPlug.java \
org/moxy/oak/commandplug/NickCommandPlug.java \
org/moxy/oak/commandplug/PluginCommandPlug.java \
org/moxy/oak/commandplug/SMCommandPlug.java \
org/moxy/oak/commandplug/ServerListCommandPlug.java \
org/moxy/oak/commandplug/HelpCommandPlug.java \
org/moxy/oak/commandplug/TopicCommandPlug.java

OAKCOMMANDPLUGS_CLASSES = \
org/moxy/oak/commandplug/CommandPlug.class \
org/moxy/oak/commandplug/ConnectionPlug.class \
org/moxy/oak/commandplug/DBCommandPlug.class \
org/moxy/oak/commandplug/DoSayCommandPlug.class \
org/moxy/oak/commandplug/ExitCommandPlug.class \
org/moxy/oak/commandplug/JoinPartCommandPlug.class \
org/moxy/oak/commandplug/KickCommandPlug.class \
org/moxy/oak/commandplug/ModerCommandPlug.class \
org/moxy/oak/commandplug/NickCommandPlug.class \
org/moxy/oak/commandplug/PluginCommandPlug.class \
org/moxy/oak/commandplug/SMCommandPlug.class \
org/moxy/oak/commandplug/ServerListCommandPlug.class \
org/moxy/oak/commandplug/HelpCommandPlug.class \
org/moxy/oak/commandplug/TopicCommandPlug.class

OAKCONFIG_SOURCES = \
org/moxy/oak/OakConfiguration.java \
org/moxy/oak/OakPreferences.java

OAKCONFIG_CLASSES = \
org/moxy/oak/OakConfiguration.class \
org/moxy/oak/OakPreferences.class

GUICONFIGURATOR_SOURCES = \
com/cjw/oak/ChoiceValuePanel.java \
com/cjw/oak/ConfigurationPanel.java \
com/cjw/oak/GUIConfigurator.java \
com/cjw/oak/LinkValuePanel.java \
com/cjw/oak/ListValuePanel.java \
com/cjw/oak/SimpleValuePanel.java \
com/cjw/oak/ValuePanel.java

GUICONFIGURATOR_CLASSES = \
com/cjw/oak/ChoiceValuePanel.class \
com/cjw/oak/ConfigurationPanel.class \
com/cjw/oak/GUIConfigurator.class \
com/cjw/oak/LinkValuePanel.class \
com/cjw/oak/ListValuePanel.class \
com/cjw/oak/SimpleValuePanel.class \
com/cjw/oak/ValuePanel.class

UTIL_CONFIG_SOURCES = \
org/moxy/util/config/BooleanType.java \
org/moxy/util/config/CharRangeType.java \
org/moxy/util/config/CharType.java \
org/moxy/util/config/CharValuesType.java \
org/moxy/util/config/ChoiceGroupItem.java \
org/moxy/util/config/Configurable.java \
org/moxy/util/config/ConfigurationSystem.java \
org/moxy/util/config/DisjunctType.java \
org/moxy/util/config/FloatOpenRangeType.java \
org/moxy/util/config/FloatRangeType.java \
org/moxy/util/config/FloatType.java \
org/moxy/util/config/FloatValuesType.java \
org/moxy/util/config/GroupItem.java \
org/moxy/util/config/IDType.java \
org/moxy/util/config/IntRangeType.java \
org/moxy/util/config/IntType.java \
org/moxy/util/config/IntValuesType.java \
org/moxy/util/config/LinkGroupItem.java \
org/moxy/util/config/ListGroupItem.java \
org/moxy/util/config/PrimitiveType.java \
org/moxy/util/config/SimpleGroupItem.java \
org/moxy/util/config/StringType.java \
org/moxy/util/config/StringValuesType.java \
org/moxy/util/config/TypeFactory.java \
org/moxy/util/config/TypeFormatException.java \
org/moxy/util/config/URLType.java \
org/moxy/util/config/UnionType.java \
org/moxy/util/config/RegExpType.java

UTIL_CONFIG_CLASSES = \
org/moxy/util/config/BooleanType.class \
org/moxy/util/config/CharRangeType.class \
org/moxy/util/config/CharType.class \
org/moxy/util/config/CharValuesType.class \
org/moxy/util/config/ChoiceGroupItem.class \
org/moxy/util/config/Configurable.class \
org/moxy/util/config/ConfigurationSystem.class \
org/moxy/util/config/DisjunctType.class \
org/moxy/util/config/FloatOpenRangeType.class \
org/moxy/util/config/FloatRangeType.class \
org/moxy/util/config/FloatType.class \
org/moxy/util/config/FloatValuesType.class \
org/moxy/util/config/GroupItem.class \
org/moxy/util/config/IDType.class \
org/moxy/util/config/IntRangeType.class \
org/moxy/util/config/IntType.class \
org/moxy/util/config/IntValuesType.class \
org/moxy/util/config/LinkGroupItem.class \
org/moxy/util/config/ListGroupItem.class \
org/moxy/util/config/PrimitiveType.class \
org/moxy/util/config/SimpleGroupItem.class \
org/moxy/util/config/StringType.class \
org/moxy/util/config/StringValuesType.class \
org/moxy/util/config/TypeFactory.class \
org/moxy/util/config/TypeFormatException.class \
org/moxy/util/config/URLType.class \
org/moxy/util/config/UnionType.class \
org/moxy/util/config/RegExpType.class

KIRKE_SOURCES = \
com/cjw/ircclient/ChatWindow.java \
com/cjw/ircclient/Client.java \
com/cjw/ircclient/ConnectDialog.java \
com/cjw/ircclient/IRCPanel.java \
com/cjw/ircclient/ListNickRenderer.java \
com/cjw/ircclient/Main.java \
com/cjw/ircclient/ConnectionsWindow.java


KIRKE_CLASSES = \
com/cjw/ircclient/ChatWindow.class \
com/cjw/ircclient/Client.class \
com/cjw/ircclient/ConnectDialog.class \
com/cjw/ircclient/IRCPanel.class \
com/cjw/ircclient/ListNickRenderer.class \
com/cjw/ircclient/Main.class \
com/cjw/ircclient/ConnectionsWindow.java

LIBDIR = .

GNUREGEXPCORECLASSES = \
	$(LIBDIR)/gnu/regexp/RESyntax.class \
	$(LIBDIR)/gnu/regexp/CharIndexed.class \
	$(LIBDIR)/gnu/regexp/REMatch.class \
	$(LIBDIR)/gnu/regexp/REToken.class \
	$(LIBDIR)/gnu/regexp/REException.class \
	$(LIBDIR)/gnu/regexp/RETokenChar.class \
	$(LIBDIR)/gnu/regexp/RETokenRange.class \
	$(LIBDIR)/gnu/regexp/RETokenPOSIX.class \
	$(LIBDIR)/gnu/regexp/RETokenOneOf.class \
	$(LIBDIR)/gnu/regexp/RETokenAny.class \
	$(LIBDIR)/gnu/regexp/RETokenRepeated.class \
	$(LIBDIR)/gnu/regexp/RETokenBackRef.class \
	$(LIBDIR)/gnu/regexp/CharIndexedString.class \
	$(LIBDIR)/gnu/regexp/CharIndexedCharArray.class \
	$(LIBDIR)/gnu/regexp/CharIndexedStringBuffer.class \
	$(LIBDIR)/gnu/regexp/CharIndexedInputStream.class \
	$(LIBDIR)/gnu/regexp/IntPair.class \
	$(LIBDIR)/gnu/regexp/CharUnit.class \
	$(LIBDIR)/gnu/regexp/RE.class \
	$(LIBDIR)/gnu/regexp/RETokenStart.class \
	$(LIBDIR)/gnu/regexp/RETokenEnd.class \
	$(LIBDIR)/gnu/regexp/REMatchEnumeration.class

GNUREGEXPCLASSES = ${GNUREGEXPCORECLASSES} \
	$(LIBDIR)/gnu/regexp/REFilterInputStream.class

GNUREGEXPUTILCLASSES = \
	$(LIBDIR)/gnu/regexp/util/Grep.class \
	$(LIBDIR)/gnu/regexp/util/Egrep.class \
	$(LIBDIR)/gnu/regexp/util/Tests.class \
	$(LIBDIR)/gnu/regexp/util/RETest.class

GNUREGEXPAPPLETCLASSES = ${GNUREGEXPCORECLASSES} \
	$(LIBDIR)/gnu/regexp/util/REApplet.class


%.class: %.java
	${JAVAC}  $<

all: framework oak kirke

framework: ${FRAMEWORK_CLASSES}

oak: utils oakcore oakplugins oakcommandplugs oaksecurity

utils: ${UTILS_CLASSES}

oakcore: ${OAKCORE_CLASSES}

oaksecurity: ${OAKSECURITY_CLASSES}

oakplugins: ${OAKPLUGINS_CLASSES}

oakcommandplugs: ${OAKCOMMANDPLUGS_CLASSES}

configutils: gnu.regexp ${UTIL_CONFIG_CLASSES}

oakconfig: ${OAKCONFIG_CLASSES}

guiconfigurator: ${GUICONFIGURATOR_CLASSES}

kirke: framework ${KIRKE_CLASSES}

gnu.regexp: $(GNUREGEXPCLASSES)

configtest: configutils oakconfig guiconfigurator

clean:
	find . -name '*.class' -exec rm {} \;
